In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from iertools.read import read_sql

In [2]:
f = "../osm/005_measures_techos/run/eplusout.sql"
casa = read_sql(f,alias=True)

In [3]:
sc = casa.construction_systems
casa.get_construction(sc)

Construction system:CAD15CMA0P7
Total thickness    :0.15 m
Total layers:[1]
InsideAbsorpVis:[0.7]
OutsideAbsorpVis:[0.7]
OutsideAbsorpSolar:[0.7]
InsideAbsorpThermal:[0.9]
OutsideRoughness:[2]

  NameMaterial  Conductivity  Density  SpecHeat  Thickness
0  CAD15cma0p7          1.73   2300.0     880.0       0.15

Construction system:LADRILLO14CM0P7
Total thickness    :0.14 m
Total layers:[1]
InsideAbsorpVis:[0.7]
OutsideAbsorpVis:[0.7]
OutsideAbsorpSolar:[0.7]
InsideAbsorpThermal:[0.9]
OutsideRoughness:[4]

      NameMaterial  Conductivity  Density  SpecHeat  Thickness
1  Ladrillo14cm0p7          0.81   1800.0     880.0       0.14

Construction system:MURO_EXT
Total thickness    :0.16 m
Total layers:[2]
InsideAbsorpVis:[0.7]
OutsideAbsorpVis:[0.7]
OutsideAbsorpSolar:[0.7]
InsideAbsorpThermal:[0.9]
OutsideRoughness:[2]

       NameMaterial  Conductivity  Density  SpecHeat  Thickness
3  Repellado2cma0p7          0.72   1860.0     840.0       0.02
2   Ladrillo14cm0p7          0.81   1800.0     880.0       0.14

In [4]:
data_casa = casa.data
data_casa

variable_name,ESTE:Zone Air Relative Humidity (%),ESTE:Zone Air Temperature (C),Id,Ib,To,OESTE:Zone Air Relative Humidity (%),OESTE:Zone Air Temperature (C)
date,,,,,,,
2006-01-01 01:00:00,29.217814,25.285324,0.0,0.0,NaN,29.103108,25.351451
2006-01-01 02:00:00,30.402719,24.565907,0.0,0.0,NaN,30.290651,24.627710
2006-01-01 03:00:00,31.642847,23.899009,0.0,0.0,NaN,31.561604,23.941854
2006-01-01 04:00:00,32.867652,23.268712,0.0,0.0,NaN,32.811816,23.296899
2006-01-01 05:00:00,34.193188,22.669409,0.0,0.0,NaN,34.154555,22.688071
...,...,...,...,...,...,...,...
2006-12-31 20:00:00,22.265630,30.061389,0.0,0.0,NaN,22.421563,29.940053
2006-12-31 21:00:00,22.615132,29.790530,0.0,0.0,NaN,22.939342,29.543357
2006-12-31 22:00:00,23.245904,29.313534,0.0,0.0,NaN,23.605552,29.047537
2006-12-31 23:00:00,24.187488,28.627683,0.0,0.0,NaN,24.527240,28.387412
2007-01-01 00:00:00,25.341702,27.826746,0.0,0.0,18.805354,25.686241,27.595284

In [5]:
fig, ax = subplots(2,1, figsize=(12,4),sharex=True)

NameError: name 'subplots' is not defined